fix
Exception in thread "Thread-14" java.lang.NoClassDefFoundError: com/android/utils/PathUtils$1
	at com.android.utils.PathUtils.deleteIfExists(PathUtils.java:47)
	at com.android.utils.PathUtils.lambda$addRemovePathHook$0(PathUtils.java:125)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.android.utils.PathUtils$1
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 3 more